### ISSUE TITLE
good addin,why stop update?

### ISSUE THREAD

**Issue by Jiuyong** [fmeus/UberInventory#3]
wait for you !
====
非常好用的插件，一直再用，但是自从 7.0 以来，就貌似用不起来了，也一直没看到新版本。如果你是原作者，希望你能继续更新。
现在在邮件或者NPC的界面上，通常看不到自己已经有多少个同样的物品了，相当之麻烦！

**Comment by fmeus** [comment]
Stopped playing WoW

**Comment by Jiuyong** [comment]
>.<!
